GET http://localhost:3000/usuarios

### BLOCO ACIMA: PUBLIC ROUTE (sem tokne) - LISTA TODOS os usuarios

POST http://localhost:3000/cadastro
Content-Type: application/json

{
    "email" : "regis@gmail.com",
    "password" : "123@123",
    "nivelacesso" : 1,
    "ativo" : "s"
}

### BLOCO ACIMA: PUBLIC ROUTE (sem tokne) - CADASTRA novo usuario

POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "regis@gmail.com",
    "password" : "123@123"
}

### BLOCO ACIMA: PUBLIC ROUTE (sem tokne) - LOGIN de usuario

GET http://localhost:3000/listar-usuarios
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI3Mjc4OTgxLCJleHAiOjE3MjcyNzkwNDF9.GvZEnEnGmcdIEYQHF0BXkKE1VjfX7nOU9JEHxOfCCWA

### BLOCO ACIMA: PRIVATE ROUTE (com token ) - LISTA TODOS os usuarios
### Pode-se passar o token, tambem, conforme abaixo:
### Authorization: Bearer <token_gerado>